package FinalActivity.tests.stepDefinitions.Interactions;// Generated by Selenium IDE

import TestComponents.BaseTest;
import FinalActivity.tests.PageActions.SelectableTestComponents;
import io.cucumber.java.Before;
import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.qameta.allure.Allure;
import org.junit.Test;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterClass;

public class SelectableCopy extends BaseTest {
  private WebDriver driver;
  JavascriptExecutor js;

//  @Before
//  public void setUp() {
//    driver = new ChromeDriver();
//    js = (JavascriptExecutor) driver;
//  }

    SelectableTestComponents selectTest = new SelectableTestComponents();
  @Test
  @Given("that I am in the DEMO homepage for Selectable activity")
  public void goToHomePageSelectable() {
    Allure.step("Navigate to DEMOQA site");
    selectTest.goToHomePage();
  }
  @When("I navigated to the Selectable activity page")
  public void goToSelectablePage() {
    Allure.step("Navigate to Selectable activity page");
    selectTest.goToSelectablePage();
  }

  @And("I verify the selectable lists as functional")
  public void selectListPage() {
    Allure.step("Verify selectable lists");
    selectTest.selectListPage();
    }

    @Then("the selectable grids must be functional")
  public void selectGridPage() {
      Allure.step("Verify selectable grids");
      selectTest.selectGridPage();
  }

  @AfterClass
  public void tearDown() {
    driver.quit();
  }
}
