package FinalActivity.tests.StepDefinitions.PracticeForm;// Generated by Selenium IDE
import TestComponents.BaseTest;
import FinalActivity.tests.PageActions.PracticeFormComponents;
//import org.FinalActivity.PracticeFormComponents;
import io.cucumber.java.Before;
import io.cucumber.java.en.*;
import org.junit.Test;
import org.junit.Before;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import org.testng.annotations.AfterClass;

public class PracticeFormTest extends BaseTest {

  JavascriptExecutor js;

  @Before
  public void setUp() {


    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;

  }

  @AfterClass
  public void tearDown() {
    driver.quit();
  }


  PracticeFormComponents practiceAct = new PracticeFormComponents();

  @Test
  @Given("that I am in the DEMO homepage for Practice activity")
  public void goToHomePage() throws InterruptedException
  {
    practiceAct.goToHomePage();
  }
  @When("I navigated to the Practice activity page")
  public void goToPracticeForm() throws InterruptedException
  {
    practiceAct.goToPracticeForm();
  }
  @And("I can enter my firstname {string}, lastname {string}, email {string}, select my gender and type my number {string}")
  public void userDetails(String firstName, String lastName, String email, String userNumber) throws InterruptedException
  {
    practiceAct.userDetails(firstName, lastName, email, userNumber);
  }

  @And("enter my birth date")
  public void birthDate() throws InterruptedException
  {
      practiceAct.birthDate();
  }
  @And("enter my hobbies")
  public void practiceHobbiesSubj() throws InterruptedException
  {
      practiceAct.practiceHobbiesSubj();
  }
  @And("upload picture")
  public void pictureUpload() throws InterruptedException
  {
      practiceAct.pictureUpload();
  }
  @And("enter my location")
  public void userLocation() throws InterruptedException
  {
      practiceAct.userLocation();
}
@Then("I must be able to submit the modal successfully")
  public void submitModal() throws InterruptedException
  {
      practiceAct.submitModal();
}
//
//    {
//      // Scroll Action for small resolutions
//      WebElement element = driver.findElement(By.tagName("body"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element, 0, 0).perform();
//      js.executeScript("window.scrollBy(0,350)", "");
//    }

  }

